Methodes on CSV file

In [2]:
import pandas as pd

In [3]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
csv_1

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [4]:
csv_1.index  # grtting index numbers

RangeIndex(start=0, stop=311, step=1)

In [5]:
csv_1.columns  # getting all the columns in the csv file

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [6]:
# looking foe a fixed data

csv_1.head(2)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17

In [7]:
csv_1.tail(3)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.6,5,6,2/21/2019,0,16
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.0,3,5,2/1/2019,0,11
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.5,5,0,1/30/2019,0,2

In [8]:
# data of the any rows
csv_1[0:6:2]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [9]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [10]:
# writing the index numbers in the array 
csv_1.index.array

<NumpyExtensionArray>
[  np.int64(0),   np.int64(1),   np.int64(2),   np.int64(3),   np.int64(4),
   np.int64(5),   np.int64(6),   np.int64(7),   np.int64(8),   np.int64(9),
 ...
 np.int64(301), np.int64(302), np.int64(303), np.int64(304), np.int64(305),
 np.int64(306), np.int64(307), np.int64(308), np.int64(309), np.int64(310)]
Length: 311, dtype: int64

In [11]:
# data as in numpy array
csv_1.to_numpy()

array([['Adinolfi, Wilson  K', 10026, 0, ..., '1/17/2019', 0, 1],
       ['Ait Sidi, Karthikeyan   ', 10084, 1, ..., '2/24/2016', 0, 17],
       ['Akinkuolie, Sarah', 10196, 1, ..., '5/15/2012', 0, 3],
       ...,
       ['Zamora, Jennifer', 10010, 0, ..., '2/21/2019', 0, 16],
       ['Zhou, Julia', 10043, 0, ..., '2/1/2019', 0, 11],
       ['Zima, Colleen', 10271, 0, ..., '1/30/2019', 0, 2]],
      shape=(311, 36), dtype=object)

In [12]:
import numpy as np
# 2nd method to convert data tonumpy array
v= np.asarray(csv_1)
print(v)

[['Adinolfi, Wilson  K' 10026 0 ... '1/17/2019' 0 1]
 ['Ait Sidi, Karthikeyan   ' 10084 1 ... '2/24/2016' 0 17]
 ['Akinkuolie, Sarah' 10196 1 ... '5/15/2012' 0 3]
 ...
 ['Zamora, Jennifer' 10010 0 ... '2/21/2019' 0 16]
 ['Zhou, Julia' 10043 0 ... '2/1/2019' 0 11]
 ['Zima, Colleen' 10271 0 ... '1/30/2019' 0 2]]

In [13]:
# sorting the data in decending order
csv_1.sort_index(axis=0,ascending=False)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1

In [15]:
# changing any data 
csv_1["Employee_Name"][0] = "Gaurav"
print(csv_1["Employee_Name"][0])

Gaurav

C:\Users\krush\AppData\Local\Temp\ipykernel_14136\1279654284.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1["Employee_Name"][0] = "Gaurav"
C:\Users\krush\AppData\Local\Temp\ipykernel_14136\1279654284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1["Employee_Name"][0] = "Gaurav"

In [ ]:
# if any row is not avaliable in the data sheet the it appears as an nan in dateframe then.
# following is th emethod to remove this row from program
csv_1.dropna(how= "any") # any missing value are removed using any keyword
csv_1.dropna(how= "all") # only missing row will be removed from dataframe single double massing values dont thkaen in address.

In [35]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
csv_1

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
1,"Ait Sidi, Karthikeyan",NaN,NaN,NaN,NaN,34000.0,1,1.0,sr.manager
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,64955.0,1,20.0,Production Technician II
3,"Alagbe,Trina",10088.0,NaN,1.0,0.0,64991.0,0,19.0,Production Technician I
4,"Anderson, Carol",10069.0,2.0,0.0,50825.0,1.0,19,NaN,NaN
5,"Anderson, Linda",NaN,0.0,NaN,0.0,57568.0,0,19.0,Production Technician I
6,"Andreola, Colby",10194.0,0.0,0.0,0.0,NaN,0,24.0,Software Engineer
7,"Athwal, Sam",10062.0,0.0,4.0,1.0,59365.0,0,19.0,NaN
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [ ]:
# removing the null value alomg perticular coloumn
#csv_1.dropna(subset=["EmpID"])  # rows in which empid has null values are there then that row get removed
#csv_1.dropna(inplace=True)  # removed all the null value containing rows
csv_1.dropna(thresh = 4)     # remove the row which having thresh no. of values

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,64955.0,1,20.0,Production Technician II
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [ ]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
# filling na values by some thing
csv_2 = csv_1.fillna("python")   # fill all na by python

# filling perticular data in perticular coloumn we will give dict
csv_3 = csv_1.fillna({"EmpID":"Not Exist", "GenderID":"001", "Salary":"000", "MaritalStatusID":"B-tech"})
#print(csv_3)

#csv_4 = csv_1.fillna(method="ffill")
#csv_4 = csv_1.fillna(method="bfill")  # the row contains all null data will fill by previous row or further row
# in above method we can also pass axis which decide the vertical and hoeoxontal fill of the data

csv_5 = csv_1.fillna(12,inplace=True)
print(csv_5)

None

In [49]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
 
csv_2 = csv_1.fillna("python", limit = 2)
print(csv_2)

              Employee_Name    EmpID MarriedID MaritalStatusID GenderID  \
0       Adinolfi, Wilson  K  10026.0       0.0             0.0      1.0
1  Ait Sidi, Karthikeyan      python    python          python   python
2         Akinkuolie, Sarah  10196.0       1.0             1.0      0.0
3              Alagbe,Trina  10088.0    python             1.0      0.0
4          Anderson, Carol   10069.0       2.0             0.0  50825.0
5         Anderson, Linda     python       0.0          python      0.0
6           Andreola, Colby  10194.0       0.0             0.0      0.0
7               Athwal, Sam  10062.0       0.0             4.0      1.0
8          Bachiochi, Linda  10114.0       0.0             0.0      0.0

    Salary  Termd PositionID                  Position
0  62506.0      0       19.0   Production Technician I
1  34000.0      1        1.0                sr.manager
2  64955.0      1       20.0  Production Technician II
3  64991.0      0       19.0   Production Technician I
4      1.0     19     python                    python
5  57568.0      0       19.0   Production Technician I
6   python      0       24.0         Software Engineer
7  59365.0      0       19.0                    python
8  47837.0      0       19.0   Production Technician I