### CSV -- Replace and Interpole functions

In [3]:
import pandas as pd

In [4]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
csv_1

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
1,"Ait Sidi, Karthikeyan",NaN,NaN,NaN,NaN,34000.0,1,1.0,sr.manager
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,64955.0,1,20.0,Production Technician II
3,"Alagbe,Trina",10088.0,NaN,1.0,0.0,64991.0,0,19.0,Production Technician I
4,"Anderson, Carol",10069.0,2.0,0.0,50825.0,1.0,19,NaN,NaN
5,"Anderson, Linda",NaN,0.0,NaN,0.0,57568.0,0,19.0,Production Technician I
6,"Andreola, Colby",10194.0,0.0,0.0,0.0,NaN,0,24.0,Software Engineer
7,"Athwal, Sam",10062.0,0.0,4.0,1.0,59365.0,0,19.0,NaN
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [8]:
# replace function
csv_2 = csv_1.replace(to_replace=0.0,value=100)   # replace 0.0 by 100 all over the program
csv_2 = csv_1.replace(to_replace="Akinkuolie",value="lakshya") 
csv_2

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
1,"Ait Sidi, Karthikeyan",NaN,NaN,NaN,NaN,34000.0,1,1.0,sr.manager
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,64955.0,1,20.0,Production Technician II
3,"Alagbe,Trina",10088.0,NaN,1.0,0.0,64991.0,0,19.0,Production Technician I
4,"Anderson, Carol",10069.0,2.0,0.0,50825.0,1.0,19,NaN,NaN
5,"Anderson, Linda",NaN,0.0,NaN,0.0,57568.0,0,19.0,Production Technician I
6,"Andreola, Colby",10194.0,0.0,0.0,0.0,NaN,0,24.0,Software Engineer
7,"Athwal, Sam",10062.0,0.0,4.0,1.0,59365.0,0,19.0,NaN
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [ ]:
csv_3 = csv_1.replace([1,2,3,4,5,6,7,8,9,0.0],100)

In [ ]:
csv_4 = csv_1.replace("[A-Za-z]","python",regex=True)
# replace all the data from a to z wil be replace by python
csv_5 = csv_1.replace({"coloumn_name":'[a-z]'},22,regex=True)  # replace all the data in perticular coloumn which contein a-z will be replaced by 22
# forwaard filling and backwad filling appears aganin but now replacing

In [9]:
# replace limited amount of data
var_6 = csv_1.replace(0.0,method="ffill",limit=2)
print(var_6)

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan         NaN        NaN              NaN       NaN
2         Akinkuolie, Sarah  10196.0        1.0              1.0       NaN
3              Alagbe,Trina  10088.0        NaN              1.0       NaN
4          Anderson, Carol   10069.0        2.0              1.0   50825.0
5         Anderson, Linda        NaN        2.0              NaN   50825.0
6           Andreola, Colby  10194.0        2.0              NaN   50825.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              4.0       1.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  64955.0      1        20.0  Production Technician II
3  64991.0      1        19.0   Production Technician I
4      1.0     19         NaN                       NaN
5  57568.0     19        19.0   Production Technician I
6      NaN     19        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_19560\2174848878.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var_6 = csv_1.replace(0.0,method="ffill",limit=2)

In [ ]:
# inplace
# replacing things in main dataset without making copy of any data set
var_1 = csv_1.replace(1,method="ffill",limit=3,inplace=True)
var_1

C:\Users\krush\AppData\Local\Temp\ipykernel_19560\1680755155.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var_1 = csv_1.replace(1,method="ffill",limit=3,inplace=True)

#### Interpolating

NameError: name 'csv_1' is not defined

In [4]:
csv_1 = pd.read_csv("C:\\Users\\krush\\Downloads\\HRDataset_v14.csv")
csv_1

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
1,"Ait Sidi, Karthikeyan",NaN,NaN,NaN,NaN,34000.0,1,1.0,sr.manager
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,NaN,1,20.0,Production Technician II
3,"Alagbe,Trina",10088.0,NaN,1.0,0.0,NaN,0,19.0,Production Technician I
4,"Anderson, Carol",10069.0,2.0,0.0,50825.0,NaN,19,NaN,NaN
5,"Anderson, Linda",NaN,0.0,NaN,0.0,NaN,0,19.0,Production Technician I
6,"Andreola, Colby",10194.0,0.0,0.0,0.0,NaN,0,24.0,Software Engineer
7,"Athwal, Sam",10062.0,0.0,4.0,1.0,59365.0,0,19.0,NaN
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [ ]:
csv_1.interpolate()    # it works only on numbers it dosnt work on alphabets

C:\Users\krush\AppData\Local\Temp\ipykernel_19392\3094693765.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,Salary,Termd,PositionID,Position
0,"Adinolfi, Wilson K",10026.0,0.0,0.0,1.0,62506.0,0,19.0,Production Technician I
1,"Ait Sidi, Karthikeyan",10111.0,0.5,0.5,0.5,34000.0,1,1.0,sr.manager
2,"Akinkuolie, Sarah",10196.0,1.0,1.0,0.0,38227.5,1,20.0,Production Technician II
3,"Alagbe,Trina",10088.0,1.5,1.0,0.0,42455.0,0,19.0,Production Technician I
4,"Anderson, Carol",10069.0,2.0,0.0,50825.0,46682.5,19,19.0,NaN
5,"Anderson, Linda",10131.5,0.0,0.0,0.0,50910.0,0,19.0,Production Technician I
6,"Andreola, Colby",10194.0,0.0,0.0,0.0,55137.5,0,24.0,Software Engineer
7,"Athwal, Sam",10062.0,0.0,4.0,1.0,59365.0,0,19.0,NaN
8,"Bachiochi, Linda",10114.0,0.0,0.0,0.0,47837.0,0,19.0,Production Technician I

In [ ]:
# following are the methods of interpolate function
csv_2 = csv_1.interpolate(method="linear")
print(csv_2)

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan     10111.0        0.5              0.5       0.5
2         Akinkuolie, Sarah  10196.0        1.0              1.0       0.0
3              Alagbe,Trina  10088.0        1.5              1.0       0.0
4          Anderson, Carol   10069.0        2.0              0.0   50825.0
5         Anderson, Linda    10131.5        0.0              0.0       0.0
6           Andreola, Colby  10194.0        0.0              0.0       0.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              0.0       0.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  38227.5      1        20.0  Production Technician II
3  42455.0      0        19.0   Production Technician I
4  46682.5     19        19.0                       NaN
5  50910.0      0        19.0   Production Technician I
6  55137.5      0        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_19392\3062301959.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_2 = csv_1.interpolate(method="linear")

In [8]:
csv_2 = csv_1.interpolate(method="linear",axis=0)  # axis 0=y-axis, axis 1 = x-axis
print(csv_2)

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan     10111.0        0.5              0.5       0.5
2         Akinkuolie, Sarah  10196.0        1.0              1.0       0.0
3              Alagbe,Trina  10088.0        1.5              1.0       0.0
4          Anderson, Carol   10069.0        2.0              0.0   50825.0
5         Anderson, Linda    10131.5        0.0              0.0       0.0
6           Andreola, Colby  10194.0        0.0              0.0       0.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              0.0       0.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  38227.5      1        20.0  Production Technician II
3  42455.0      0        19.0   Production Technician I
4  46682.5     19        19.0                       NaN
5  50910.0      0        19.0   Production Technician I
6  55137.5      0        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_19392\83911039.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_2 = csv_1.interpolate(method="linear",axis=0)  # axis 0=y-axis, axis 1 = x-axis

In [6]:
# limit method- limiting the number of updates
csv_2 = csv_1.interpolate(limit=2,limit_direction="forward",axis=0)
print(csv_2)

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan     10111.0        0.5              0.5       0.5
2         Akinkuolie, Sarah  10196.0        1.0              1.0       0.0
3              Alagbe,Trina  10088.0        1.5              1.0       0.0
4          Anderson, Carol   10069.0        2.0              0.0   50825.0
5         Anderson, Linda    10131.5        0.0              0.0       0.0
6           Andreola, Colby  10194.0        0.0              0.0       0.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              0.0       0.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  38227.5      1        20.0  Production Technician II
3  42455.0      0        19.0   Production Technician I
4      NaN     19        19.0                       NaN
5      NaN      0        19.0   Production Technician I
6      NaN      0        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_16060\3345639488.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_2 = csv_1.interpolate(limit=2,limit_direction="forward",axis=0)

In [8]:
# limit area

csv_3 = csv_1.interpolate(limit_area="inside")
print(csv_3)
# inside - fill all the null data inside the dataframe
# outside - dosnt fill any null data/ no filling occures

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan     10111.0        0.5              0.5       0.5
2         Akinkuolie, Sarah  10196.0        1.0              1.0       0.0
3              Alagbe,Trina  10088.0        1.5              1.0       0.0
4          Anderson, Carol   10069.0        2.0              0.0   50825.0
5         Anderson, Linda    10131.5        0.0              0.0       0.0
6           Andreola, Colby  10194.0        0.0              0.0       0.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              0.0       0.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  38227.5      1        20.0  Production Technician II
3  42455.0      0        19.0   Production Technician I
4  46682.5     19        19.0                       NaN
5  50910.0      0        19.0   Production Technician I
6  55137.5      0        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_16060\900155964.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_3 = csv_1.interpolate(limit_area="inside")

In [9]:
# inplace method
# If inplae = True --> there is change in original dataset
# inplace = False --> there is a copy of original dataset will produce and it will update accordingly

csv_4 = csv_1.interpolate(limit_direction="both",limit=2,inplace=False)
print(csv_4)

              Employee_Name    EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026.0        0.0              0.0       1.0
1  Ait Sidi, Karthikeyan     10111.0        0.5              0.5       0.5
2         Akinkuolie, Sarah  10196.0        1.0              1.0       0.0
3              Alagbe,Trina  10088.0        1.5              1.0       0.0
4          Anderson, Carol   10069.0        2.0              0.0   50825.0
5         Anderson, Linda    10131.5        0.0              0.0       0.0
6           Andreola, Colby  10194.0        0.0              0.0       0.0
7               Athwal, Sam  10062.0        0.0              4.0       1.0
8          Bachiochi, Linda  10114.0        0.0              0.0       0.0

    Salary  Termd  PositionID                  Position
0  62506.0      0        19.0   Production Technician I
1  34000.0      1         1.0                sr.manager
2  38227.5      1        20.0  Production Technician II
3  42455.0      0        19.0   Production Technician I
4      NaN     19        19.0                       NaN
5  50910.0      0        19.0   Production Technician I
6  55137.5      0        24.0         Software Engineer
7  59365.0      0        19.0                       NaN
8  47837.0      0        19.0   Production Technician I

C:\Users\krush\AppData\Local\Temp\ipykernel_16060\2235134067.py:5: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_4 = csv_1.interpolate(limit_direction="both",limit=2,inplace=False)

### Merger of 2 data_frames and csv files

In [ ]:
var1 = pd.DataFrame({"a":[1,3,2,5],"b":[6,5,9,6]})
var2 = pd.DataFrame({"a":[1,3,2,5],"c":[9,4,3,7]})

print(pd.merge(var1, var2, on="a"))

#there will be the merger of similar datatypes
var1 = pd.DataFrame({"a":[1,3,2,5],"b":[6,5,9,6]})
var2 = pd.DataFrame({"a":[1,3,2,0],"c":[9,4,3,7]})

print(pd.merge(var1, var2, on="a"))

   a  b  c
0  1  6  9
1  3  5  4
2  2  9  3
3  5  6  7
   a  b  c
0  1  6  9
1  3  5  4
2  2  9  3

In [ ]:
# merger with missing data
var3 = pd.merge(var1, var2, how = "left")
print(var3)
var4 = pd.merge(var1, var2, how = "right")
print(var4)
var5 = pd.merge(var1, var2, how = "outer", indicator=True)  # indicator is for finding which data is missing 
print(var5)

   a  b    c
0  1  6  9.0
1  3  5  4.0
2  2  9  3.0
3  5  6  NaN
   a    b  c
0  1  6.0  9
1  3  5.0  4
2  2  9.0  3
3  0  NaN  7
   a    b    c
0  0  NaN  7.0
1  1  6.0  9.0
2  2  9.0  3.0
3  3  5.0  4.0
4  5  6.0  NaN

In [22]:
var1 = pd.DataFrame({"A":[1,3,2,5],"B":[6,5,9,6]})
var2 = pd.DataFrame({"A":[1,3,2,5],"B":[9,4,3,7]})

pd.merge(var1, var2, left_index=True, right_index=True, suffixes=("name", "ID"))

   Aname  Bname  AID  BID
0      1      6    1    9
1      3      5    3    4
2      2      9    2    3
3      5      6    5    7

In [25]:
# Concat
# series
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([17,25,34,43,52,61])

pd.concat([s1,s2])

0     1
1     2
2     3
3     4
4     5
5     6
0    17
1    25
2    34
3    43
4    52
5    61
dtype: int64

In [30]:
d1 = pd.DataFrame({"A":[1,3,2,5],"B":[6,5,9,6]})
d2 = pd.DataFrame({"A":[1,3,2],"B":[9,4,3]})

pd.concat([d1,d2], axis=0)

   A  B
0  1  6
1  3  5
2  2  9
3  5  6
0  1  9
1  3  4
2  2  3